### ISSUE TITLE
colour member pagina

### ISSUE THREAD

**Issue by RickVellingaa** [RickVellingaa/connect-your-tribe-squad-page#19]
Colour van member als achtergrond van hun persoonlijke pagina maken

**Comment by Siem-P** [comment]
Fixed the member background color;

Solution:
https://github.com/RickVellingaa/connect-your-tribe-squad-page/blob/08495c6a585ae97ebe7dac44000dda29020b93d1/views/member.ejs#L4

Adding '?' to member.colour?.hex

This checks whether colour has a value or not. If it doesn't it will display a default colour.
