### ISSUE TITLE
nav

### ISSUE THREAD

**Issue by FouadTaissate** [RickVellingaa/connect-your-tribe-squad-page#20]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/112860051/220589966-464ea089-4f93-4fd8-b877-f19f33224505.png">
<img width="902" alt="image" src="https://user-images.githubusercontent.com/112860051/220590089-01da67f9-5744-408c-87bf-58ec736905db.png">
er is een extra nav tag maar misschien kan er wel 1 weg

**Comment by RickVellingaa** [comment]
Gefixt!
